# -*- coding: utf-8 -*-
"""CSE420 lab 3 at lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1evl8rqWU0f-lfLg6qBloAXan6ufRh7xZ
"""

import re

regex=[]
no_of_reg = int(input("Number of inputs you want to take for regex: "))
for i in range(0, no_of_reg):
    ele = re.compile(input())
 
    regex.append(ele)

print(regex)

example=[]
no_of_example = int(input("Number of inputs you want to take as example: "))
for i in range(0, no_of_example):
    ele2 = input()
 
    example.append(ele2)

print(example)

"""
for i in range(len(regex)):
  regex[i]=re.compile(regex[i]) #no more as it has taken in in ele
  """
#print(regex[i])
#result = []
for i in range(len(example)):
  no_match = 0
  for j in range(len(regex)):
    #print(f"{example[i]} regex {regex[j]}")
    if(regex[j].match(example[i])):
      print(f"Yes, {j+1}")
      break
    else:
      no_match+=1
  
  if(no_match==no_of_reg):
    print(f"NO, 0")